// <auto-generated />
using System;
using EdicoesEmMassa.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EdicoesEmMassa.Migrations
{
    [DbContext(typeof(bancoContext))]
    [Migration("20220614035819_CriacaoInicial")]
    partial class CriacaoInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EdicoesEmMassa.Entity.Incubadora", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TemperaturaAtual")
                        .HasColumnType("double precision");

                    b.Property<double>("TemperaturaIdeal")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Incubadora");
                });

            modelBuilder.Entity("EdicoesEmMassa.Entity.TemperaturaHistorico", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdIncubadora")
                        .HasColumnType("integer");

                    b.Property<double>("TemperaturaAtual")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("IdIncubadora");

                    b.ToTable("TemperaturaHistorico");
                });

            modelBuilder.Entity("EdicoesEmMassa.Entity.TemperaturaHistorico", b =>
                {
                    b.HasOne("EdicoesEmMassa.Entity.Incubadora", "Incubadora")
                        .WithMany("Historicos")
                        .HasForeignKey("IdIncubadora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incubadora");
                });

            modelBuilder.Entity("EdicoesEmMassa.Entity.Incubadora", b =>
                {
                    b.Navigation("Historicos");
                });
#pragma warning restore 612, 618
        }
    }
}
