// <auto-generated />
using System;
using EdicoesEmMassa.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EdicoesEmMassa.Migrations
{
    [DbContext(typeof(bancoContext))]
    [Migration("20220611001918_CriandoTabelaTemperatura")]
    partial class CriandoTabelaTemperatura
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EdicoesEmMassa.Model.IncubadoraModel", b =>
                {
                    b.Property<int>("IdIncubadora")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CodIncubadora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TemperaturaFixada")
                        .HasColumnType("float");

                    b.HasKey("IdIncubadora");

                    b.ToTable("Incubadora");
                });

            modelBuilder.Entity("EdicoesEmMassa.Model.TemperaturaModel", b =>
                {
                    b.Property<int>("IdTemperatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IncubadoraIdIncubadora")
                        .HasColumnType("int");

                    b.Property<double>("TemperaturaAtual")
                        .HasColumnType("float");

                    b.HasKey("IdTemperatura");

                    b.HasIndex("IncubadoraIdIncubadora");

                    b.ToTable("Temperatura");
                });

            modelBuilder.Entity("EdicoesEmMassa.Model.TemperaturaModel", b =>
                {
                    b.HasOne("EdicoesEmMassa.Model.IncubadoraModel", "Incubadora")
                        .WithMany()
                        .HasForeignKey("IncubadoraIdIncubadora");

                    b.Navigation("Incubadora");
                });
#pragma warning restore 612, 618
        }
    }
}
